### ISSUE TITLE
 asyncio-nats-client version required to build worker

### ISSUE THREAD

**Issue by seb-835** [grycap/oscar-worker#18]
Hi, 
@srisco @alpegon 
thanks a lot for the project, so helpfull to make openfaas async job !!!
 
is it possible to know the version of  asyncio-nats-client library you use to build grycap/oscar-worker:latest ? 

Because,  trying to rebuild  the image using the github code failed on : 

```
...
Step 7/15 : RUN pip3 install -r requirements.txt  && pip3 install pyinstaller
...
Collecting asyncio-nats-client>=0.7.0 (from asyncio-nats-streaming->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/91/71/1e70cfeb15ac082a039a6011fa1c6684b55239dd8edd411a871d2c35aab2/asyncio-nats-client-0.11.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-qfhas1fm/asyncio-nats-client/setup.py", line 2, in <module>
        from nats.aio.client import __version__
      File "/tmp/pip-build-qfhas1fm/asyncio-nats-client/nats/__init__.py", line 16, in <module>
        from .aio.client import Client as NATS
      File "/tmp/pip-build-qfhas1fm/asyncio-nats-client/nats/aio/client.py", line 155
        return f"<nats client v{__version__}>"
                                             ^
    SyntaxError: invalid syntax
``` 

Thanks

**Comment by seb-835** [comment]
i got it compile by adding the following version in requirement file :

asyncio-nats-client==0.10.0
pyinstaller==3.6

can you confirm before i made a pull request to fix it ?

**Comment by srisco** [comment]
Hello @seb-835,

Thanks for contacting us. Yes, I can confirm that the version of `asyncio-nats-client` was indeed `0.10.0`. I assume you are interested in keeping the nats queue to support a specific use case (multi-input processing). Unfortunately, oscar-worker is no longer supported because OSCAR >= `v2.0.0` can natively create jobs from API requests. I hope you can at least adapt it to your needs.

Cheers.
